version: 2
updates:
  # TypeScript templates
  - package-ecosystem: "npm"
    directories:
      - "/typescript/*"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    allow:
      - dependency-name: "@nitric/suga-client"

  # Python Django template
  - package-ecosystem: "pip"
    directory: "/python/django"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    allow:
      - dependency-name: "suga-client"

  # Python uv template
  - package-ecosystem: "uv"
    directory: "/python/uv"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "suga-client"

  # Go templates
  - package-ecosystem: "gomod"
    directories:
      - "/go/*"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "github.com/nitrictech/suga/*"