version: 2
updates:
  # TypeScript templates
  - package-ecosystem: "npm"
    directories:
      - "/typescript/*"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    allow:
      - dependency-name: "@nitric/suga-client"

  # Python templates
  - package-ecosystem: "pip"
    directories:
      - "/python/*"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    allow:
      - dependency-name: "suga-client"

  # Go templates
  - package-ecosystem: "gomod"
    directories:
      - "/go/*"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "github.com/nitrictech/suga/*"